# Generated by Django 4.2.11 on 2025-04-06 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_name_gin_indx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReplenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.IntegerField()),
                ('provider_email', models.EmailField(max_length=254)),
                ('provider_name', models.CharField(max_length=40)),
                ('address', models.CharField(blank=True, max_length=70, null=True)),
                ('provider_number', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
