# Generated by Django 4.2.11 on 2025-04-08 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productreplenishment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreplenishment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='products.product'),
        ),
    ]
